title: Marblehead Budget Data
description: Open data and charts about Marblehead, MA municipal finances
last_updated: April 16, 2026
version: "1.1.0"
url: https://marbleheaddata.org
baseurl: ""

plugins: []

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "index.html"
    values:
      layout: home
  - scope:
      path: "charts"
    values:
      layout: chart
      community_pulse: off-sections

exclude:
  - README.md
  - STYLE_GUIDE.md
  - LICENSE
  - docs/
  - data/acfr/
  - data/budgets/
  - community-pulse/
  - node_modules/
