// Data-driven fill for the choice-bucketed checkbook sketch.
//
// On page load, fetch /data/checkbook_view.json (generated by
// scripts/build_checkbook_view.py from the latest checkbook CSV snapshot),
// then walk [data-fill] elements to substitute live numbers.
//
// Graceful degradation: if the fetch fails or a particular key is missing,
// the hardcoded fallback content in the HTML stays put — the page still
// renders something meaningful.

(function () {
  'use strict';

  function fmtUsd(n) {
    if (n === null || n === undefined) return '';
    var abs = Math.abs(n);
    if (abs >= 1e6) return '$' + (n / 1e6).toFixed(2).replace(/\.?0+$/, '') + 'M';
    if (abs >= 1e3) return '$' + Math.round(n / 1e3) + 'K';
    return '$' + Math.round(n).toLocaleString();
  }
  function fmtUsdLong(n) {
    if (n === null || n === undefined) return '';
    return '$' + Math.round(n).toLocaleString();
  }
  function fmtPct(n) {
    if (n === null || n === undefined) return '';
    return (n * 100).toFixed(1) + '%';
  }
  function fmtPctTight(n) {
    if (n === null || n === undefined) return '';
    return Math.round(n * 100) + '%';
  }
  function fmtInt(n) {
    if (n === null || n === undefined) return '';
    return n.toLocaleString();
  }
  function fmtDate(iso) {
    if (!iso) return '';
    var parts = iso.split('-');
    var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return months[+parts[1] - 1] + ' ' + (+parts[2]) + ', ' + parts[0];
  }
  function fmtDaysAgo(days) {
    if (days === null || days === undefined) return '';
    if (days === 0) return 'today';
    if (days === 1) return '1d ago';
    return days + 'd ago';
  }
  var FORMATTERS = {
    'usd':       fmtUsd,
    'usd-long':  fmtUsdLong,
    'pct':       fmtPct,
    'pct-tight': fmtPctTight,
    'int':       fmtInt,
    'date':      fmtDate,
    'days-ago':  fmtDaysAgo,
    'raw':       function (x) { return x === undefined || x === null ? '' : String(x); },
  };

  function resolvePath(obj, path) {
    var keys = path.split('.');
    for (var i = 0; i < keys.length; i++) {
      if (obj === null || obj === undefined) return undefined;
      var k = keys[i];
      // Allow [filter:value] segments like buckets[key:ballot].amount
      var bracket = k.match(/^(\w+)\[(\w+):([^\]]+)\]$/);
      if (bracket) {
        var arrName = bracket[1], filterKey = bracket[2], filterValue = bracket[3];
        var arr = obj[arrName];
        if (!Array.isArray(arr)) return undefined;
        obj = arr.find(function (item) {
          return String(item[filterKey]) === filterValue;
        });
        continue;
      }
      obj = obj[k];
    }
    return obj;
  }

  function fillElement(el, view) {
    var spec = el.getAttribute('data-fill');
    if (!spec) return;
    var parts = spec.split('|');
    var path = parts[0];
    var fmt = (parts[1] || 'raw').trim();
    var formatter = FORMATTERS[fmt] || FORMATTERS.raw;
    var value = resolvePath(view, path);
    if (value === undefined || value === null) return;
    el.textContent = formatter(value);
  }

  function setSegmentFlex(view) {
    document.querySelectorAll('[data-flex-from]').forEach(function (el) {
      var path = el.getAttribute('data-flex-from');
      var value = resolvePath(view, path);
      if (typeof value === 'number') {
        // Share is 0-1, segment flex is its percentage
        el.style.flex = String(value * 100);
      }
    });
  }

  function refreshFreshness(view) {
    var chip = document.querySelector('[data-freshness]');
    if (!chip || !view.snapshot || !view.snapshot.date) return;
    var snap = new Date(view.snapshot.date + 'T00:00:00');
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    var days = Math.round((today - snap) / 86400000);
    chip.textContent = 'Snapshot: ' + fmtDate(view.snapshot.date)
      + ' · ' + (days === 0 ? 'fresh today' : days + ' days old');
  }

  // --- Status chip label per inferred project status ----------------------
  var STATUS_LABEL = {
    'active':      'Active',
    'wrapping':    'Wrapping',
    'engineering': 'Engineering phase',
    'closing':     'Closing out',
    'unknown':     'Status unknown',
  };

  function renderBallotProjects(view) {
    var list = document.querySelector('.projects-list');
    var tmpl = document.querySelector('.project-template');
    if (!list || !tmpl || !view.ballot_projects) return;
    list.innerHTML = '';  // wipe hardcoded fallback
    view.ballot_projects.forEach(function (p) {
      var node = tmpl.content.cloneNode(true);
      var pname = node.querySelector('.pname');
      var pmeta = node.querySelector('.pmeta');
      var pstatus = node.querySelector('.pstatus');
      var pnote = node.querySelector('.pnote');
      var pwhen = node.querySelector('.pwhen');

      pname.textContent = p.display || p.fund_id;

      // Ballot link + purpose
      var ballotLink = document.createElement('a');
      ballotLink.href = 'https://dls-gw.dor.state.ma.us/reports/rdpage.aspx?rdreport=votes.prop2_5.debtexclusionvotes';
      ballotLink.textContent = 'Ballot ' + (p.ballot_date ? p.ballot_date.replace(/^(\d+)-(\d+)-(\d+)$/, '$2/$3/$1') : '') + ' passed';
      pmeta.innerHTML = '';
      pmeta.appendChild(ballotLink);
      if (p.purpose) {
        pmeta.appendChild(document.createTextNode(' · ' + p.purpose));
      }

      // Status chip
      pstatus.className = 'pstatus ' + p.status;
      var statusText = STATUS_LABEL[p.status] || p.status;
      if (p.days_since_last_paid !== null && p.days_since_last_paid !== undefined) {
        statusText += ' · last paid ' + fmtDaysAgo(p.days_since_last_paid);
      }
      pstatus.textContent = statusText;

      // Note: FY26 spend + payment count + top vendors + first/last dates
      var noteParts = [];
      noteParts.push('FY26 spend: <span class="v">' + fmtUsd(p.amount) + '</span>');
      noteParts.push(' across <b>' + fmtInt(p.row_count) + ' payments</b>');
      if (p.top_vendors && p.top_vendors.length) {
        var topVendor = p.top_vendors[0];
        var topShare = Math.round(topVendor.share * 100);
        if (p.top_vendors.length === 1 || topShare >= 90) {
          noteParts.push(', <b>' + topShare + '% to ' + topVendor.name + '</b>');
        } else {
          var lead = p.top_vendors.slice(0, 4).map(function (v) {
            return v.name + ' (' + fmtUsd(v.amount) + ')';
          }).join(', ');
          noteParts.push(' to multiple vendors: ' + lead + '.');
        }
      }
      if (p.first_paid && p.last_paid) {
        noteParts.push(' First FY26 payment ' + fmtDate(p.first_paid) + '; most recent ' + fmtDate(p.last_paid) + '.');
      }
      pnote.innerHTML = noteParts.join('');

      // When-set context line
      pwhen.textContent = p.context || '';
      if (!p.context) pwhen.style.display = 'none';

      list.appendChild(node);
    });
  }

  function renderWhatMoved(view) {
    var section = document.querySelector('#what-moved');
    if (!section) return;
    if (!view.what_moved) {
      // No prior snapshot available — hide the section rather than show
      // stale hardcoded numbers that pretend to be live
      section.style.display = 'none';
      return;
    }
    var w = view.what_moved;
    var lede = section.querySelector('p');
    var ul = section.querySelector('ul');
    var srcLine = section.querySelector('p .src');

    // Heading
    var h3 = section.querySelector('h3');
    if (h3) {
      h3.textContent = 'What moved since the last snapshot ('
        + fmtDate(w.prior_snapshot_date) + ' → ' + fmtDate(w.current_snapshot_date) + ')';
    }
    if (lede) {
      var lineHtml =
        '<b>' + fmtUsd(w.new_amount) + '</b> in new payments across <b>'
        + fmtInt(w.new_rows) + '</b> new ledger rows. <b>'
        + fmtInt(w.edited_or_removed_rows) + '</b> prior rows were edited or reversed (normal end-of-month reconciliation). The motion concentrated in fewer than 10 vendors.';
      // Preserve a sources line if present
      lede.innerHTML = lineHtml +
        '<span class="src" style="display: block; margin-top: 6px;">Sources: ' +
        '<a href="/data/checkbook_view.json">current view JSON</a> derived from the latest checkbook CSV snapshot.</span>';
    }
    if (ul) {
      ul.innerHTML = '';
      w.top_movers.slice(0, 8).forEach(function (m) {
        var li = document.createElement('li');
        li.innerHTML =
          '<span><span class="name">' + m.vendor + '</span>'
          + '<span class="src">' + fmtInt(m.rows) + ' new ' + (m.rows === 1 ? 'row' : 'rows') + '</span></span>'
          + '<span class="v">+' + fmtUsd(m.delta) + '</span>';
        ul.appendChild(li);
      });
    }
  }

  function init() {
    fetch('/data/checkbook_view.json', { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (view) {
        document.querySelectorAll('[data-fill]').forEach(function (el) {
          fillElement(el, view);
        });
        setSegmentFlex(view);
        refreshFreshness(view);
        renderBallotProjects(view);
        renderWhatMoved(view);
        document.documentElement.setAttribute('data-view-loaded', 'true');
      })
      .catch(function (err) {
        // Hardcoded fallback content stays; just log
        console.warn('checkbook-view: live data unavailable, using fallback', err);
      });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
