// Data-driven fill for the choice-bucketed checkbook sketch.
//
// On page load, fetch /data/checkbook_view.json (generated by
// scripts/build_checkbook_view.py from the latest checkbook CSV snapshot),
// then walk [data-fill] elements to substitute live numbers.
//
// Graceful degradation: if the fetch fails or a particular key is missing,
// the hardcoded fallback content in the HTML stays put — the page still
// renders something meaningful.

(function () {
  'use strict';

  function fmtUsd(n) {
    if (n === null || n === undefined) return '';
    var abs = Math.abs(n);
    if (abs >= 1e6) return '$' + (n / 1e6).toFixed(2).replace(/\.?0+$/, '') + 'M';
    if (abs >= 1e3) return '$' + Math.round(n / 1e3) + 'K';
    return '$' + Math.round(n).toLocaleString();
  }
  function fmtUsdLong(n) {
    if (n === null || n === undefined) return '';
    return '$' + Math.round(n).toLocaleString();
  }
  function fmtPct(n) {
    if (n === null || n === undefined) return '';
    return (n * 100).toFixed(1) + '%';
  }
  function fmtPctTight(n) {
    if (n === null || n === undefined) return '';
    return Math.round(n * 100) + '%';
  }
  function fmtInt(n) {
    if (n === null || n === undefined) return '';
    return n.toLocaleString();
  }
  function fmtDate(iso) {
    if (!iso) return '';
    var parts = iso.split('-');
    var months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return months[+parts[1] - 1] + ' ' + (+parts[2]) + ', ' + parts[0];
  }
  function fmtDaysAgo(days) {
    if (days === null || days === undefined) return '';
    if (days === 0) return 'today';
    if (days === 1) return '1d ago';
    return days + 'd ago';
  }
  var FORMATTERS = {
    'usd':       fmtUsd,
    'usd-long':  fmtUsdLong,
    'pct':       fmtPct,
    'pct-tight': fmtPctTight,
    'int':       fmtInt,
    'date':      fmtDate,
    'days-ago':  fmtDaysAgo,
    'raw':       function (x) { return x === undefined || x === null ? '' : String(x); },
  };

  function resolvePath(obj, path) {
    var keys = path.split('.');
    for (var i = 0; i < keys.length; i++) {
      if (obj === null || obj === undefined) return undefined;
      var k = keys[i];
      // Allow [filter:value] segments like buckets[key:ballot].amount
      var bracket = k.match(/^(\w+)\[(\w+):([^\]]+)\]$/);
      if (bracket) {
        var arrName = bracket[1], filterKey = bracket[2], filterValue = bracket[3];
        var arr = obj[arrName];
        if (!Array.isArray(arr)) return undefined;
        obj = arr.find(function (item) {
          return String(item[filterKey]) === filterValue;
        });
        continue;
      }
      obj = obj[k];
    }
    return obj;
  }

  function fillElement(el, view) {
    var spec = el.getAttribute('data-fill');
    if (!spec) return;
    var parts = spec.split('|');
    var path = parts[0];
    var fmt = (parts[1] || 'raw').trim();
    var formatter = FORMATTERS[fmt] || FORMATTERS.raw;
    var value = resolvePath(view, path);
    if (value === undefined || value === null) return;
    el.textContent = formatter(value);
  }

  function setSegmentFlex(view) {
    document.querySelectorAll('[data-flex-from]').forEach(function (el) {
      var path = el.getAttribute('data-flex-from');
      var value = resolvePath(view, path);
      if (typeof value === 'number') {
        // Share is 0-1, segment flex is its percentage
        el.style.flex = String(value * 100);
      }
    });
  }

  function refreshFreshness(view) {
    var chip = document.querySelector('[data-freshness]');
    if (!chip || !view.snapshot || !view.snapshot.date) return;
    var snap = new Date(view.snapshot.date + 'T00:00:00');
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    var days = Math.round((today - snap) / 86400000);
    chip.textContent = 'Snapshot: ' + fmtDate(view.snapshot.date)
      + ' · ' + (days === 0 ? 'fresh today' : days + ' days old');
  }

  function init() {
    fetch('/data/checkbook_view.json', { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      })
      .then(function (view) {
        document.querySelectorAll('[data-fill]').forEach(function (el) {
          fillElement(el, view);
        });
        setSegmentFlex(view);
        refreshFreshness(view);
        document.documentElement.setAttribute('data-view-loaded', 'true');
      })
      .catch(function (err) {
        // Hardcoded fallback content stays; just log
        console.warn('checkbook-view: live data unavailable, using fallback', err);
      });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
