// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOWED_ORIGIN: "https://marbleheaddata.org" | "*";
	SITE_BASE_URL: "https://marbleheaddata.org";
	GITHUB_REPO: "agbaber/marblehead";
	GITHUB_BRANCH: "main";
	MAIL_FROM: "Marblehead Data <meetings@marbleheaddata.org>" | "Marblehead Data (staging) <meetings@marbleheaddata.org>";
	MAIL_REPLY_TO: "agbaber@gmail.com";
	TURNSTILE_TEST_BYPASS_TOKEN: "TEST-OK";
	DB: D1Database;
}
